FROM ghcr.io/dockhippie/golang:1.26-arm64@sha256:de5b90ab0bfa9f95e79d56cb77e2a09cdd4350bdae0c37794ff4ec43414adf3c AS build

# renovate: datasource=github-tags depName=gohugoio/hugo
ENV HUGO_VERSION=0.163.3

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@v${HUGO_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:fd6b64c28999f89881292745d098065d8114d2b1a05f1176d2ab60c87a96b78e

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
