FROM ghcr.io/dockhippie/golang:1.26-amd64@sha256:7cf4f363d18c06d3becc79807ca0f12f4c5283ecda4feddbda6ea03d86ecd083 AS build

# renovate: datasource=github-tags depName=gohugoio/hugo
ENV HUGO_VERSION=0.163.3

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@v${HUGO_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:521c63eb29b1cc282ec04e4286d00d4f6f71c190bca72fc5d2d4fd0c4df8bdf9

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
