FROM ghcr.io/dockhippie/golang:1.26-arm@sha256:09f43b619ad55f37d37820f72de3b2f436ee24b94f2910f926acd5e8d0f83052 AS build

# renovate: datasource=github-tags depName=gohugoio/hugo
ENV HUGO_VERSION=0.163.3

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@v${HUGO_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:c4b2fdf3f0038145ae5a9a4ce399ba885d3797ce3526962a0be7cae57e09db70

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go sassc git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
