FROM ghcr.io/dockhippie/golang:1.26-arm64@sha256:89466dee5eb49e3e18d4311b1806bea29178b29fea3c9a93f15c44d3476cd5df AS build

# renovate: datasource=github-tags depName=gohugoio/hugo
ENV HUGO_VERSION=0.163.3

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@v${HUGO_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:9a26a5670a11ca47049dc53cad3b012074b038bd0e4c59af8c92f81be4d5defb

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
