FROM ghcr.io/dockhippie/golang:1.25-arm64@sha256:65517e6b5906c6569a1820ab60481581b6d42775f686301b017f1686ab3fc5ca AS build

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@latest

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:608d26dd6471939dc977322205d3a67ef7b101eb5aea108606dd5e368bb4c9d1

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
