FROM ghcr.io/dockhippie/golang:1.26-arm@sha256:03f93cdea98b22ffeba95b586a62f141e1409c58e1c88aa64fa617c4e2b612c7 AS build

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@latest

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:cf28f1c99c7942d0b14bac79e9c57b540cff3a4cde232a857531fcdfbfd0f198

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go sassc git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
