FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:1b536758129b361a29bf4edc2ce8da570aa592b191297fd8966414cb964cf289 AS build

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@latest

FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:2c004c3066c04ee318d4839c43f015e1de28ad370cd4be3cb07bf26a3eccaa6d

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
