FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:496ead6bf45265ac7ad13da62b8b7d8f1eea801a24acef1dce4ee7bf16c0d055 AS build

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@latest

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:ef4289b793c6e795ffef683dfef53bca95e3d399a05306d56633f86fddd8437b

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
