FROM ghcr.io/dockhippie/golang:1.25-arm64@sha256:5bfca1d07b58f471cafab9b91d594388b9289c61048d934e3e76860671300a0b AS build

ENV GO_ENABLED=1

RUN apk add --no-cache build-base && \
  go install \
  -ldflags '-s -w -X "github.com/gohugoio/hugo/common/hugo.vendorInfo=dockhippie" -X "github.com/gohugoio/hugo/common/hugo.buildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"' \
  -tags extended,withdeploy \
  github.com/gohugoio/hugo@latest

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:eed5c5fc267853036f5bba25706d7833e8ebf7f24cb1f3f393463f9fe15057f1

VOLUME ["/srv/app"]
WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["server"]

RUN apk update && \
  apk upgrade && \
  apk add make go dart-sass@testing git && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/hugo /usr/bin/hugo
COPY ./overlay /
